"""A Python client for the Agent Host Protocol.

The wire types, the seven reducers, version negotiation, the error codes and the
transport abstraction all come from `agent_host_protocol`, the layer this shares
with the sibling host. Nothing protocol-shaped is defined here (ADR 0001).

```python
import asyncio
from agent_host_client import connect, Delta, ToolCallReady, TurnCompleted


async def main() -> None:
    async with connect("ws://localhost:4321") as client:
        async with await client.create_session(provider="echo", cwd=".") as session:
            async for event in session.prompt("Summarise README.md"):
                match event:
                    case Delta(text=t):
                        print(t, end="", flush=True)
                    case ToolCallReady() as call:
                        call.approve()
                    case TurnCompleted():
                        print()
```
"""

from __future__ import annotations

from agent_host_client.api import (
    ApprovalPolicy,
    Changeset,
    ChangesetFile,
    ChangesetInfo,
    ChangesetOperation,
    Chat,
    ChatWatch,
    Client,
    ClientClaim,
    Delta,
    FileSide,
    InputRequested,
    Reasoning,
    Reconnected,
    ResponsePartAdded,
    Session,
    SessionClaim,
    Terminal,
    TerminalClaim,
    TerminalClaimed,
    TerminalCleared,
    TerminalCommand,
    TerminalCommandDetected,
    TerminalCommandExecuted,
    TerminalCommandFinished,
    TerminalCwdChanged,
    TerminalEvent,
    TerminalExited,
    TerminalInfo,
    TerminalNotHeld,
    TerminalOutput,
    TerminalRefused,
    TerminalResized,
    TerminalStream,
    TerminalTitleChanged,
    TitleChanged,
    ToolCallCompleted,
    ToolCallContentChanged,
    ToolCallDelta,
    ToolCallReady,
    ToolCallResultReview,
    ToolCallRunning,
    ToolCallStarted,
    ToolInfo,
    TurnCancelled,
    TurnCompleted,
    TurnEvent,
    TurnFailed,
    TurnInProgress,
    TurnStarted,
    TurnStream,
    UnansweredToolCallError,
    UnknownEvent,
    UnknownTerminalEvent,
    Usage,
    approve_all,
    ask,
    auto,
    claim_from_wire,
    connect,
    deny_all,
    describe_claim,
    event_for,
    new_terminal_uri,
    terminal_uris,
    text_range,
)
from agent_host_client.client import (
    AhpClient,
    AhpClientError,
    ClientClosed,
    ClientConfig,
    InvalidArgument,
    RequestTimeout,
    RpcError,
    Subscription,
    TransportError,
    is_session_gone,
)

__version__ = "0.1.0.dev0"

__all__ = [
    "AhpClient",
    "AhpClientError",
    "ApprovalPolicy",
    "Changeset",
    "ChangesetFile",
    "ChangesetInfo",
    "ChangesetOperation",
    "Chat",
    "ChatWatch",
    "Client",
    "ClientClaim",
    "ClientClosed",
    "ClientConfig",
    "Delta",
    "FileSide",
    "InputRequested",
    "InvalidArgument",
    "Reasoning",
    "Reconnected",
    "RequestTimeout",
    "ResponsePartAdded",
    "RpcError",
    "Session",
    "SessionClaim",
    "Subscription",
    "Terminal",
    "TerminalClaim",
    "TerminalClaimed",
    "TerminalCleared",
    "TerminalCommand",
    "TerminalCommandDetected",
    "TerminalCommandExecuted",
    "TerminalCommandFinished",
    "TerminalCwdChanged",
    "TerminalEvent",
    "TerminalExited",
    "TerminalInfo",
    "TerminalNotHeld",
    "TerminalOutput",
    "TerminalRefused",
    "TerminalResized",
    "TerminalStream",
    "TerminalTitleChanged",
    "TitleChanged",
    "ToolCallCompleted",
    "ToolCallContentChanged",
    "ToolCallDelta",
    "ToolCallReady",
    "ToolCallResultReview",
    "ToolCallRunning",
    "ToolCallStarted",
    "ToolInfo",
    "TransportError",
    "TurnCancelled",
    "TurnCompleted",
    "TurnEvent",
    "TurnFailed",
    "TurnInProgress",
    "TurnStarted",
    "TurnStream",
    "UnansweredToolCallError",
    "UnknownEvent",
    "UnknownTerminalEvent",
    "Usage",
    "__version__",
    "approve_all",
    "ask",
    "auto",
    "claim_from_wire",
    "connect",
    "deny_all",
    "describe_claim",
    "event_for",
    "is_session_gone",
    "new_terminal_uri",
    "terminal_uris",
    "text_range",
]
