"""Generated from the vendored upstream TypeScript. DO NOT EDIT.

Regenerate with `python scripts/generate_tables.py`.

Source: spec/v0.7.0 (ea6fae670c4012721fdc02d587b3a46ecdc871c0)
"""

from __future__ import annotations

from typing import Final

#: The protocol version upstream's own source tree declares at the pinned tag.
#: This is NOT what we speak -- see agent_host_protocol.types.versions.
UPSTREAM_PROTOCOL_VERSION: Final = '0.7.0'

#: Every version the upstream client at the pinned tag will negotiate.
UPSTREAM_SUPPORTED_PROTOCOL_VERSIONS: Final[tuple[str, ...]] = ('0.7.0', '0.6.0', '0.5.2', '0.5.1')

#: Every action's wire string, from `export const enum ActionType`.
ACTION_TYPES: Final[frozenset[str]] = frozenset([
    'annotations/entryRemoved',
    'annotations/entrySet',
    'annotations/removed',
    'annotations/set',
    'annotations/updated',
    'changeset/cleared',
    'changeset/contentChanged',
    'changeset/fileRemoved',
    'changeset/fileSet',
    'changeset/filesReviewChanged',
    'changeset/operationStatusChanged',
    'changeset/operationsChanged',
    'changeset/statusChanged',
    'chat/activityChanged',
    'chat/delta',
    'chat/draftChanged',
    'chat/error',
    'chat/inputAnswerChanged',
    'chat/inputCompleted',
    'chat/inputRequested',
    'chat/pendingMessageRemoved',
    'chat/pendingMessageSet',
    'chat/queuedMessagesReordered',
    'chat/reasoning',
    'chat/responsePart',
    'chat/toolCallAuthRequired',
    'chat/toolCallAuthResolved',
    'chat/toolCallComplete',
    'chat/toolCallConfirmed',
    'chat/toolCallContentChanged',
    'chat/toolCallDelta',
    'chat/toolCallReady',
    'chat/toolCallResultConfirmed',
    'chat/toolCallStart',
    'chat/truncated',
    'chat/turnCancelled',
    'chat/turnComplete',
    'chat/turnStarted',
    'chat/turnsLoaded',
    'chat/usage',
    'chat/workingDirectoryRemoved',
    'chat/workingDirectorySet',
    'resourceWatch/changed',
    'root/activeSessionsChanged',
    'root/agentsChanged',
    'root/configChanged',
    'root/terminalsChanged',
    'session/activeClientRemoved',
    'session/activeClientSet',
    'session/activityChanged',
    'session/changesetsChanged',
    'session/chatAdded',
    'session/chatRemoved',
    'session/chatUpdated',
    'session/configChanged',
    'session/creationFailed',
    'session/customizationRemoved',
    'session/customizationToggled',
    'session/customizationUpdated',
    'session/customizationsChanged',
    'session/defaultChatChanged',
    'session/inputNeededRemoved',
    'session/inputNeededSet',
    'session/isArchivedChanged',
    'session/isReadChanged',
    'session/mcpServerStartRequested',
    'session/mcpServerStateChanged',
    'session/mcpServerStopRequested',
    'session/metaChanged',
    'session/ready',
    'session/serverToolsChanged',
    'session/titleChanged',
    'session/workingDirectoryRemoved',
    'session/workingDirectorySet',
    'terminal/claimed',
    'terminal/cleared',
    'terminal/commandDetectionAvailable',
    'terminal/commandExecuted',
    'terminal/commandFinished',
    'terminal/cwdChanged',
    'terminal/data',
    'terminal/exited',
    'terminal/input',
    'terminal/resized',
    'terminal/titleChanged',
])

#: Whether a client may originate each action. Upstream: "Servers SHOULD call
#: this to validate incoming `dispatchAction` requests and reject any action the
#: client is not allowed to originate." Unknown actions are NOT dispatchable.
IS_CLIENT_DISPATCHABLE: Final[dict[str, bool]] = {
    'root/agentsChanged': False,
    'root/activeSessionsChanged': False,
    'root/terminalsChanged': False,
    'root/configChanged': True,
    'session/ready': False,
    'session/creationFailed': False,
    'session/chatAdded': False,
    'session/chatRemoved': False,
    'session/chatUpdated': False,
    'session/defaultChatChanged': False,
    'session/titleChanged': True,
    'session/serverToolsChanged': False,
    'session/activeClientSet': True,
    'session/activeClientRemoved': True,
    'session/workingDirectorySet': True,
    'session/workingDirectoryRemoved': True,
    'session/inputNeededSet': False,
    'session/inputNeededRemoved': False,
    'session/customizationsChanged': False,
    'session/customizationToggled': True,
    'session/customizationUpdated': False,
    'session/customizationRemoved': False,
    'session/mcpServerStateChanged': False,
    'session/mcpServerStartRequested': True,
    'session/mcpServerStopRequested': True,
    'session/isReadChanged': True,
    'session/isArchivedChanged': True,
    'session/activityChanged': False,
    'session/changesetsChanged': False,
    'session/configChanged': True,
    'session/metaChanged': False,
    'chat/turnStarted': True,
    'chat/delta': False,
    'chat/responsePart': False,
    'chat/toolCallStart': False,
    'chat/toolCallDelta': False,
    'chat/toolCallReady': False,
    'chat/toolCallConfirmed': True,
    'chat/toolCallComplete': True,
    'chat/toolCallResultConfirmed': True,
    'chat/toolCallContentChanged': True,
    'chat/toolCallAuthRequired': False,
    'chat/toolCallAuthResolved': False,
    'chat/turnComplete': False,
    'chat/turnCancelled': True,
    'chat/error': False,
    'chat/activityChanged': False,
    'chat/workingDirectorySet': True,
    'chat/workingDirectoryRemoved': True,
    'chat/usage': False,
    'chat/reasoning': False,
    'chat/pendingMessageSet': True,
    'chat/pendingMessageRemoved': True,
    'chat/queuedMessagesReordered': True,
    'chat/draftChanged': True,
    'chat/inputRequested': False,
    'chat/inputAnswerChanged': True,
    'chat/inputCompleted': True,
    'chat/truncated': True,
    'chat/turnsLoaded': False,
    'changeset/statusChanged': False,
    'changeset/fileSet': False,
    'changeset/fileRemoved': False,
    'changeset/filesReviewChanged': True,
    'changeset/contentChanged': False,
    'changeset/operationsChanged': False,
    'changeset/operationStatusChanged': False,
    'changeset/cleared': False,
    'annotations/set': True,
    'annotations/updated': True,
    'annotations/removed': True,
    'annotations/entrySet': True,
    'annotations/entryRemoved': True,
    'terminal/data': False,
    'terminal/input': True,
    'terminal/resized': True,
    'terminal/claimed': True,
    'terminal/titleChanged': True,
    'terminal/cwdChanged': False,
    'terminal/exited': False,
    'terminal/cleared': True,
    'terminal/commandDetectionAvailable': False,
    'terminal/commandExecuted': False,
    'terminal/commandFinished': False,
    'resourceWatch/changed': False,
}

#: Action -> the protocol version that introduced it. Drives the outbound filter
#: implementing "the host only sends action types known to the negotiated
#: version" (docs/specification/versioning.md).
ACTION_INTRODUCED_IN: Final[dict[str, str]] = {
    'root/agentsChanged': '0.1.0',
    'root/activeSessionsChanged': '0.1.0',
    'session/ready': '0.1.0',
    'session/creationFailed': '0.1.0',
    'session/chatAdded': '0.4.0',
    'session/chatRemoved': '0.4.0',
    'session/chatUpdated': '0.4.0',
    'session/defaultChatChanged': '0.4.0',
    'session/titleChanged': '0.1.0',
    'session/serverToolsChanged': '0.1.0',
    'session/activeClientSet': '0.5.0',
    'session/activeClientRemoved': '0.5.0',
    'session/workingDirectorySet': '0.7.0',
    'session/workingDirectoryRemoved': '0.7.0',
    'session/inputNeededSet': '0.5.1',
    'session/inputNeededRemoved': '0.5.1',
    'session/customizationsChanged': '0.1.0',
    'session/customizationToggled': '0.1.0',
    'session/customizationUpdated': '0.1.0',
    'session/customizationRemoved': '0.2.0',
    'session/mcpServerStateChanged': '0.3.0',
    'session/mcpServerStartRequested': '0.5.2',
    'session/mcpServerStopRequested': '0.5.2',
    'session/isReadChanged': '0.1.0',
    'session/isArchivedChanged': '0.1.0',
    'session/activityChanged': '0.1.0',
    'session/changesetsChanged': '0.2.0',
    'session/configChanged': '0.1.0',
    'session/metaChanged': '0.1.0',
    'chat/turnStarted': '0.4.0',
    'chat/delta': '0.4.0',
    'chat/responsePart': '0.4.0',
    'chat/toolCallStart': '0.4.0',
    'chat/toolCallDelta': '0.4.0',
    'chat/toolCallReady': '0.4.0',
    'chat/toolCallConfirmed': '0.4.0',
    'chat/toolCallComplete': '0.4.0',
    'chat/toolCallResultConfirmed': '0.4.0',
    'chat/toolCallContentChanged': '0.4.0',
    'chat/toolCallAuthRequired': '0.6.0',
    'chat/toolCallAuthResolved': '0.6.0',
    'chat/turnComplete': '0.4.0',
    'chat/turnCancelled': '0.4.0',
    'chat/error': '0.4.0',
    'chat/activityChanged': '0.5.0',
    'chat/workingDirectorySet': '0.7.0',
    'chat/workingDirectoryRemoved': '0.7.0',
    'chat/usage': '0.4.0',
    'chat/reasoning': '0.4.0',
    'chat/pendingMessageSet': '0.4.0',
    'chat/pendingMessageRemoved': '0.4.0',
    'chat/queuedMessagesReordered': '0.4.0',
    'chat/draftChanged': '0.5.0',
    'chat/inputRequested': '0.4.0',
    'chat/inputAnswerChanged': '0.4.0',
    'chat/inputCompleted': '0.4.0',
    'chat/truncated': '0.4.0',
    'chat/turnsLoaded': '0.5.1',
    'changeset/statusChanged': '0.2.0',
    'changeset/fileSet': '0.2.0',
    'changeset/fileRemoved': '0.2.0',
    'changeset/filesReviewChanged': '0.6.0',
    'changeset/contentChanged': '0.4.0',
    'changeset/operationsChanged': '0.2.0',
    'changeset/operationStatusChanged': '0.3.0',
    'changeset/cleared': '0.2.0',
    'annotations/set': '0.4.0',
    'annotations/updated': '0.4.0',
    'annotations/removed': '0.4.0',
    'annotations/entrySet': '0.4.0',
    'annotations/entryRemoved': '0.4.0',
    'root/terminalsChanged': '0.1.0',
    'root/configChanged': '0.1.0',
    'terminal/data': '0.1.0',
    'terminal/input': '0.1.0',
    'terminal/resized': '0.1.0',
    'terminal/claimed': '0.1.0',
    'terminal/titleChanged': '0.1.0',
    'terminal/cwdChanged': '0.1.0',
    'terminal/exited': '0.1.0',
    'terminal/cleared': '0.1.0',
    'terminal/commandDetectionAvailable': '0.1.0',
    'terminal/commandExecuted': '0.1.0',
    'terminal/commandFinished': '0.1.0',
    'resourceWatch/changed': '0.2.0',
}

#: Server->client notification method -> the protocol version that introduced
#: it (`ServerNotificationMap` minus `action`, which ACTION_INTRODUCED_IN
#: versions per action type). Upstream's `isNotificationKnownToVersion` is a
#: `<=` compare against the negotiated version; every method here predates the
#: oldest negotiable version at this pin, so the filter only bites after a pin
#: bump lands a newer notification -- vendored now so that bump cannot land
#: without the table.
NOTIFICATION_INTRODUCED_IN: Final[dict[str, str]] = {
    'root/sessionAdded': '0.1.0',
    'root/sessionRemoved': '0.1.0',
    'root/sessionSummaryChanged': '0.1.0',
    'root/progress': '0.5.0',
    'auth/required': '0.1.0',
    'otlp/exportLogs': '0.2.0',
    'otlp/exportTraces': '0.2.0',
    'otlp/exportMetrics': '0.2.0',
}

#: Standard JSON-RPC 2.0 error codes.
JSON_RPC_ERROR_CODES: Final[dict[str, int]] = {
    'ParseError': -32700,
    'InvalidRequest': -32600,
    'MethodNotFound': -32601,
    'InvalidParams': -32602,
    'InternalError': -32603,
}

#: AHP application error codes. Do not invent parallel ones.
AHP_ERROR_CODES: Final[dict[str, int]] = {
    'SessionNotFound': -32001,
    'ProviderNotFound': -32002,
    'SessionAlreadyExists': -32003,
    'TurnInProgress': -32004,
    'UnsupportedProtocolVersion': -32005,
    'ContentNotFound': -32006,
    'AuthRequired': -32007,
    'NotFound': -32008,
    'PermissionDenied': -32009,
    'AlreadyExists': -32010,
    'Conflict': -32011,
}
