#!/usr/bin/env bash
# Regenerate tests/conformance/fixtures/js-semantics.json from the pinned
# upstream TypeScript reducers.
#
# Run this after an upstream pin bump. It needs Node and the checkout at
# `.research/agent-host-protocol` -- the test it feeds is offline and needs
# neither.
#
# The oracle is the reference reducer itself, not our reading of it: these cases
# exist precisely because the fixture corpus's comparator cannot express the
# difference between an absent key and an explicit null, so a hand-written
# expectation would be begging the question.
set -euo pipefail
cd "$(dirname "$0")/.."

UPSTREAM=.research/agent-host-protocol/types
if [ ! -d "$UPSTREAM" ]; then
  echo "missing $UPSTREAM -- clone upstream at the pinned tag first" >&2
  exit 1
fi

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

python scripts/js_semantics_cases.py > "$WORK/cases.jsonl"

# The pinned sources are .ts but import each other with .js specifiers, so a
# resolver hook is needed to load them in place.
node --experimental-transform-types \
  --import "data:text/javascript,import{register}from'node:module';import{pathToFileURL}from'node:url';register('$PWD/scripts/js_semantics_loader.mjs',pathToFileURL('./'));" \
  scripts/js_semantics_oracle.mjs < "$WORK/cases.jsonl" > "$WORK/ts.jsonl"

python - "$WORK" <<'PY'
import json, sys
work = sys.argv[1]
cases = {json.loads(l)["name"]: json.loads(l) for l in open(f"{work}/cases.jsonl")}
out = []
for line in open(f"{work}/ts.jsonl"):
    ts = json.loads(line)
    if not ts["ok"]:
        raise SystemExit(f"the reference reducer threw on {ts['name']}: {ts['error']}")
    case = cases[ts["name"]]
    out.append({
        "name": ts["name"],
        "reducer": case["reducer"],
        "initial": case["initial"],
        "actions": case["actions"],
        "expected": ts["state"],
    })
doc = {
    "note": (
        "Generated by scripts/regenerate_js_semantics.sh from the pinned upstream "
        "TypeScript reducers. `expected` is the reference reducer's own output, "
        "passed through JSON.stringify -- so an absent key means the reference "
        "really produced `undefined` there, and an explicit null means it really "
        "produced null. Do not hand-edit."
    ),
    "cases": out,
}
with open("tests/conformance/fixtures/js-semantics.json", "w") as f:
    json.dump(doc, f, indent=1)
    f.write("\n")
print(f"{len(out)} cases regenerated")
PY
